plugins:
  - rubocop-rake
AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - bin/**/*
    - vendor/**/*
  TargetRubyVersion: 3.4

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/MethodLength:
  Max: 15
